### ISSUE TITLE
Deployment procedure should be refactored

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#10]
Now, deployment is complicated and duplicated. Scripts and configurations should be used from repository. At least with some `debug` option. Now, we have to modify scripts in deploy directory.

Plugins also should not be duplicated in deployment directory. They should be submodules or simplinks.

**Comment by vmordan** [comment]
I think this is done with the latest commits - plugins are installed via symlink and you can make launches in CV directory. @PavelAndrianov PTAL
