### ISSUE TITLE
Support verification of several projects

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#20]
The task is large, so better to discuss first.

The idea is to have an ability to check several projects in one run. For example, a work of applications in an OS. So, we need to build several projects independently, then merge build commands, then construct a single CIL file. After that we should add an entry point for applications and run the verifier.

The key challenge is separated configurations for projects. So, we have to store different patches or entrypoints from different plugins, likely. And then combine them together.

**Comment by vmordan** [comment]
@PavelAndrianov As I understand the whole support is now incleded in the master branch.

**Comment by PavelAndrianov** [comment]
Yes, now it works.
