### ISSUE TITLE
Bug in error trace comparison

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#23]
I created a pattern of error trace:
```
func1
  __ERROR__
func2
 __ERROR__
```
I set similarity 100 and `partial include ordered`. I expected, that the pattern is applied to those traces, which contain two threads and the first one has `func` in the trace, and the second thread - `func2`. However, the pattern was applied to the trace, which contains `func1` and `func2` in the one thread and absolutely different the other thread. 

Likely, you searched the patterns independently. Need somehow consider, that the patterns should be in the different threads.

**Comment by vmordan** [comment]
Fixed in klever repository. @PavelAndrianov PTAL

**Comment by PavelAndrianov** [comment]
Works on the saved example. In case of other problems, reopen the issue.
