### ISSUE TITLE
Failure in case of aspect file is not set

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#3]
If CIF is used as a preprocessor, it requires an aspect. If it is not set, None is used, and then the preparator fails, as NoneType object is inside cif_args list. So, the warning message is confusing. Better to fail, if we use CIF without aspect earlier.

And a more practical solution is to generate an empty aspect file with a warning, that "no aspect is set, use empty one".
```
before: file ("$this")
{
}
```

**Comment by vmordan** [comment]
Fixed in commit c5ce8b38
