### ISSUE TITLE
Problem with new python in web-interface

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#5]
I have an Ubuntu 20.04 with python 3.8. And some CV components do not work with it. In some cases I can choose the version, for example, run `python3.5 ./scripts/launcher ...`. It's OK. But in some cases I can not. For example, web interface starts only with command start.sh with preset `python3`, which is in my case python3.8. Right now, I have to change the script.

**Comment by PavelAndrianov** [comment]
The same issue with deployment script.

**Comment by vmordan** [comment]
Package `python-psycopg2` is not required on Ubuntu 18 and later versions, since it is included in `libpq-dev`. Thus it works  with python 3.8

**Comment by vmordan** [comment]
@PavelAndrianov is this issue still present with Ubuntu 22?

**Comment by PavelAndrianov** [comment]
Actually, I do not remember. Let's reopen the issue, if necessary.
