### ISSUE TITLE
Improve witness search

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#6]
For benchmark-visualization witnesses should be placed in a strict hardcoded paths, assuming a particular benchexec version. For other version the structure of the output paths are different, thus right now the witnesses can be found only for cloud launch. 
The idea is to have a soft mode, when the witnesses will be searched in all subdirectories. For example, via `find`. Then we may miss some relation between benchmark, rundefinition and files, but at least we will be able upload results for marking.

**Comment by vmordan** [comment]
Implemented in commit a47d8a6
