### ISSUE TITLE
Support for notes

### ISSUE THREAD

**Issue by mutilin** [ispras/cv#61]
1.  [x] Комментарий от cpachecker показывать в дополнение к коду, так как это дополнительная информация к коду, а не замена кода. Кроме модельных LDV и emg (и каких еще?) комментариев.
2. [ ] CPAchecker выдает hide=false на все комментарии (это скорее всего неверно)
3. [ ] Не щелкается последняя строчка (добавить)
4. [ ] Показывать hide=false немного другим цветом
5. [x] Поддерживать несколько ноутов на одну строчку (одинакового или разного level)

**Comment by mutilin** [comment]
CPAchecker outputs hide=false for all comments
 - [ ] workaround - скрывать все `level=2` вне зависимости от `hide=false`
 - [ ] поправить `cpachecker hide=true/false`
 - [ ] обновить `cpachecker в klever`

**Comment by vmordan** [comment]
Workaround for `hide=false` - https://github.com/vmordan/cvv/pull/6

**Comment by vmordan** [comment]
Support of several notes: https://github.com/ispras/cv/pull/63

**Comment by vmordan** [comment]
All CPAchecker note come with `hide=false`, this attribute is for Klever only. If we set note to `hide=true` then comment will not be shown.
