### ISSUE TITLE
Bug in tag creation

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#7]
I tried to create a new tag on an error trace page (not on a special tag page). I described a new tag and push "create". Then a message "Unknown error" is shown and the dialog window is not hide. So, I have to click "close". I supposed, that the tag was no created, but on a tag page I suprisingly found my tag.

**Comment by PavelAndrianov** [comment]
The problem is reproduced for eny change in tags even on tag page. So, change of a parent causes an "Unknown error", and one has to close the dialog window. And the desired change is suddenly applied after the page refresh.

**Comment by vmordan** [comment]
It looks like this happens if there is only one registered user in the system. In this case some options are not shown (such as "Users can modify"). I guess, this bug was in original klever. 

Quick-fix: create a new user ('Sign out' and then 'Register').

**Comment by PavelAndrianov** [comment]
Technically, I had two users: admin and manager. But, yes, one more user helps. Thanks!
