### ISSUE TITLE
Entrypoint config races is reverted

### ISSUE THREAD

**Issue by PavelAndrianov** [ispras/cv#9]
Now entrypoints are generated for `races` only if the corresponding option `race` is `false`. Should be vice versa. Need to update all configurations.

**Comment by vmordan** [comment]
The descriptionof entrypoints was refactored,, I think it is done now@PavelAndrianov PTAL

**Comment by PavelAndrianov** [comment]
There is some confusion with `ignored` and `not ignored`. From the one side it is useful, from the other side not easy to understand for a particular entrypoint.
However, the initial issue is complete.
